name: GitHub Actions Demo

on:
  push: 
    branches:
      - main
    paths-ignore:
      - '.gitignore/**'
  pull_request:
    branches:
      - main

  schedule:
    - cron: '15 6 * * 0'
  
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The tags are ${{ github.event_name }} The tags are ${{ github.ref }}"
      
      - uses: actions/checkout@v3.3.0

      - run: echo "The repository ${{ github.repository }} contains the following files:"
            tree      

